version: 0.2
phases:
  install:
    commands:
      - echo Installing dependencies...
      - yum install -y docker
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login-password --region ap-south-1) | docker login --username AWS --password-stdin <your-account-id>.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t spring-boot-app .
      - docker tag spring-boot-app:latest <your-account-id>.dkr.ecr.ap-south-1.amazonaws.com/spring-boot-app:latest
  post_build:
    commands:
      - echo Pushing the image to ECR...
      - docker push <your-account-id>.dkr.ecr.ap-south-1.amazonaws.com/spring-boot-app:latest
